import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const eslintConfig = [
  {
    // next-env.d.ts is auto-generated by Next.js; do not lint it
    ignores: ["next-env.d.ts", ".next/**", "node_modules/**"],
  },
  ...nextVitals,
  ...nextTypeScript,
  {
    rules: {
      "react-hooks/immutability": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
];

export default eslintConfig;
